export const organizationCallSigns = [
	{ organization: 'Technisches Hilfswerk (THW)', tmo_dmo: 'Heros' },
	{ organization: 'Feuerwehren (BF/FF/PF)', tmo_dmo: 'Florian' },
	{ organization: 'Deutsches Rotes Kreuz (DRK)', tmo_dmo: 'Rotkreuz' },
	{ organization: 'Johanniter-Unfall-Hilfe (JUH)', tmo_dmo: 'Akkon' },
	{ organization: 'Deutsche Lebens-Rettungs-Gesellschaft (DLRG)', tmo_dmo: 'Pelikan' },
	{ organization: 'Arbeiter-Samariter-Bund (ASB)', tmo_dmo: 'Sama' },
	{ organization: 'Malteser-Hilfsdienst (MHD)', tmo_dmo: 'Johannes' },
	{ organization: 'Katastrophenschutzbehörde (KatS)', tmo_dmo: 'Kater' },
	{ organization: 'Bergwacht (BW)', tmo_dmo: 'Bergwacht' },
	{ organization: 'Wasserwacht (WW)', tmo_dmo: 'Wasserwacht' },
	{ organization: 'Rettungs-Transport-Hubschrauber (RTH)', tmo_dmo: 'Christoph' }
];

export const thwUnits = [
	{
		unit: 'Führungsstellen als TEL/EL/EAL/UEAL/BR (im Einsatz)',
		number: '10 - 15',
		code: ['10', '11', '12', '13', '14', '15']
	},
	{ unit: 'Zugtrupp des Fachzug Führung/Kommunikation', number: '16', code: '16' },
	{ unit: 'Fachgruppe Führungsunterstützung', number: '17', code: '17' },
	{ unit: 'Fachgruppe Kommunikation, Typ A', number: '18', code: '18' },
	{ unit: 'Fachgruppe Kommunikation, Typ B', number: '19', code: '19' },
	{ unit: 'Zugtrupp des 1. Technischer Zug', number: '21', code: '21' },
	{ unit: 'Bergungsgruppe im 1. Technischen Zug', number: '22', code: '22' },
	{ unit: 'Zweite Bergungsgruppe im 1. Technischen Zug', number: '23', code: '23' },
	{
		unit: 'Fachgruppe Notversorgung/Notinstandsetzung im 1. Technischen Zug',
		number: '24',
		code: '24'
	},
	{ unit: 'Zugtrupp des 2. Technischer Zug', number: '26', code: '26' },
	{ unit: 'Bergungsgruppe im 2. Technischen Zug', number: '27', code: '27' },
	{
		unit: 'Fachgruppe Notversorgung/Notinstandsetzung im 2. Technischen Zug',
		number: '28',
		code: '28'
	},
	{ unit: 'Fachgruppe Infrastruktur', number: '31', code: '31' },
	{ unit: 'Fachgruppe Elektroversorgung', number: '32', code: '32' },
	{ unit: 'Fachgruppe Trinkwasserversorgung', number: '33', code: '33' },
	{ unit: 'Fachgruppe Sprengen', number: '35', code: '35' },
	{ unit: 'Fachgruppe Wassergefahren, Typ A', number: '36', code: '36' },
	{ unit: 'Fachgruppe Wassergefahren, Typ B', number: '37', code: '37' },
	{ unit: 'Fachgruppe Schwere Bergung, Typ A', number: '38', code: '38' },
	{ unit: 'Fachgruppe Schwere Bergung, Typ B', number: '39', code: '39' },
	{ unit: 'Fachgruppe Räumen Typ B (Radlader)', number: '41', code: '41' },
	{ unit: 'Fachgruppe Räumen Typ A (Bagger)', number: '42', code: '42' },
	{ unit: 'Fachgruppe Räumen Typ C (Teleskoplader)', number: '43', code: '43' },
	{ unit: 'Fachgruppe Ortung, Typ A', number: '44', code: '44' },
	{ unit: 'Fachgruppe Ortung, Typ B', number: '45', code: '45' },
	{ unit: 'Fachgruppe Ortung, Typ C', number: '46', code: '46' },
	{ unit: 'Fachgruppe Wasserschaden/Pumpen, Typ A', number: '47', code: '47' },
	{ unit: 'Fachgruppe Wasserschaden/Pumpen, Typ B', number: '48', code: '48' },
	{ unit: 'Fachgruppe Wasserschaden/Pumpen, Typ C', number: '49', code: '49' },
	{ unit: 'Fachgruppe Brückenbau', number: '54', code: '54' },
	{ unit: 'Fachgruppe Ölschaden, Typ A', number: '55', code: '55' },
	{ unit: 'Fachgruppe Ölschaden, Typ B', number: '56', code: '56' },
	{ unit: 'Fachgruppe Ölschaden, Typ C', number: '57', code: '57' },
	{ unit: 'Fachgruppe Bergungstauchen', number: '58', code: '58' },
	{ unit: 'Zugtrupp des Fachzug Logistik', number: '61', code: '61' },
	{ unit: 'Trupp Schwerer Transport', number: '62', code: '62' },
	{ unit: 'Fachgruppe Logistik Materialwirtschaft', number: '63', code: '63' },
	{ unit: 'Fachgruppe Logistik-Verpflegung', number: '64', code: '64' },
	{ unit: 'Trupp Logistik Sonderfahrzeuge nur im Einsatz', number: '65', code: '65' },
	{ unit: 'Zugtrupp (Sonstige Einheiten, z.B. 3. TZ)', number: '71', code: '71' },
	{ unit: '1. Gruppe (Sonstige Einheiten, z.B. 3. TZ)', number: '72', code: '72' },
	{ unit: '2. Gruppe (Sonstige Einheiten, z.B. 3. TZ)', number: '73', code: '73' },
	{ unit: 'Trupp Mobiler Hochwasserpegel', number: '74', code: '74' },
	{ unit: 'Trupp Einsatzstellensicherung', number: '75', code: '75' },
	{ unit: 'Trupp Unbemannte Luftfahrtsysteme', number: '76', code: '76' },
	{ unit: 'Einheiten Örtliche Gefahrenabwehr', number: '79', code: '79' },
	{ unit: 'THW-Leitung', number: '81', code: '81' },
	{ unit: 'THW-AZ', number: '82', code: '82' },
	{ unit: 'THW-LogH / LogZ', number: '83', code: '83' },
	{ unit: 'Landesverband (Dienststelle)', number: '84', code: '84' },
	{ unit: 'Regionalstelle', number: '85', code: '85' },
	{ unit: 'Ortsverband', number: '86', code: '86' },
	{ unit: 'SEEBA', number: '91', code: '91' },
	{ unit: 'SEELift', number: '92', code: '92' },
	{ unit: 'SEEWA', number: '93', code: '93' },
	{
		unit: 'Führungsstellen im Einsatz',
		number: '94 - 99',
		code: ['94', '95', '96', '97', '98', '99']
	}
];

export const vehiclePersonNumbers = [
	{
		description: 'UEAL/BR im Einsatz',
		number: '1-9',
		code: ['1', '2', '3', '4', '5', '6', '7', '8', '9']
	},
	{ description: 'MTW eines Zugtrupp', number: '10', code: '10' },
	{ description: 'FüKW', number: '11', code: '11' },
	{ description: 'FüKomKW Nur FGr F', number: '12', code: '12' },
	{ description: 'FmKW Nur FGr K', number: '13', code: '13' },
	{ description: 'FüKomKW Nur FGr F - als Übergangslösung', number: '14', code: '14' },
	{ description: 'FmKW Nur FGr K - als Übergangslösung', number: '15', code: '15' },
	{ description: 'MastKW Nur FGr K(B)', number: '17', code: '17' },
	{ description: 'PKW', number: '21-24', code: ['21', '22', '23', '24'] },
	{ description: 'MTW', number: '25-28', code: ['25', '26', '27', '28'] },
	{ description: 'MLW 1 ehem. ITrKW', number: '31', code: '31' },
	{ description: 'MLW 2 LKW 5t Unimog', number: '32', code: '32' },
	{ description: 'MLW 3 ehem. MKW - Platzhalter', number: '33', code: '33' },
	{ description: 'MLW 4 LKW 14t', number: '34', code: '34' },
	{ description: 'MLW 5 Kleintransporter', number: '35', code: '35' },
	{ description: 'LKW ≤ 7t', number: '41', code: '41' },
	{ description: 'LKW > 7t', number: '42', code: '42' },
	{ description: 'LKW mit Ladebordwand', number: '43', code: '43' },
	{ description: 'LKW mit Ladekran < 190 kNm', number: '44', code: '44' },
	{ description: 'LKW mit Ladekran ≥ 190 kNm', number: '45', code: '45' },
	{ description: 'LKW mit Ladekran, geländegängig', number: '46', code: '46' },
	{ description: 'Autokran', number: '47', code: '47' },
	{ description: 'Zweiter LKW mit Ladebordwand in einer Gruppe', number: '49', code: '49' },
	{ description: 'GKW', number: '51', code: '51' },
	{ description: 'GKW II der neuen Generation', number: '52', code: '52' },
	{ description: 'Alter GKW II als Übergangslösung', number: '53', code: '53' },
	{ description: 'MzKW', number: '54', code: '54' },
	{ description: 'MzGW', number: '55', code: '55' },
	{ description: 'Sonstige Gerätewagen', number: '56', code: '56' },
	{ description: 'BelKW Beleuchtungskraftwagen', number: '57', code: '57' },
	{ description: 'LKW Kipper < 9 t', number: '61', code: '61' },
	{ description: 'LKW Kipper ≥ 9 t', number: '62', code: '62' },
	{ description: 'LKW Kipper mit Ladekran Lkr < 190 kNm', number: '63', code: '63' },
	{ description: 'LKW Kipper mit Ladekran Lkr ≥ 190 kNm', number: '64', code: '64' },
	{ description: 'Wechselladefahrzeug WLF', number: '65', code: '65' },
	{ description: 'Wechselladefahrzeug WLF Ladekran', number: '66', code: '66' },
	{ description: 'Wechselladefahrzeug WLF Wechselpritsche', number: '67', code: '67' },
	{ description: 'LKW Sattel-KFZ', number: '68', code: '68' },
	{ description: 'Bergungsräumgerät Bagger', number: '71', code: '71' },
	{ description: 'Bergungsräumgerät Radlader', number: '72', code: '72' },
	{ description: 'Bergungsräumgerät Teleskoplader', number: '73', code: '73' },
	{ description: 'Bergungsräumgerät sonstige Baumaschinen', number: '74', code: '74' },
	{ description: 'ERS Schreitbagger', number: '75', code: '75' },
	{ description: 'Sonstige Kraftfahrzeuge', number: '77', code: '77' },
	{ description: 'Sonstige Fahrzeuge', number: '78', code: '78' },
	{ description: 'Bus', number: '79', code: '79' },
	{ description: 'Mehrzweckarbeitsboot', number: '81, 82', code: ['81', '82'] },
	{ description: 'Mehrzweckponton', number: '83, 84', code: ['83', '84'] },
	{ description: 'Sonstige Wasserfahrzeuge', number: '85, 86', code: ['85', '86'] },
	{ description: 'Führungskraft', number: '91', code: '91' },
	{ description: 'Stellvertreter von 91', number: '92', code: '92' },
	{ description: '2. Stellvertreter von 91', number: '93', code: '93' },
	{ description: 'Fachberater', number: '94, 95', code: ['94', '95'] },
	{ description: 'Technischer Berater', number: '96', code: '96' },
	{ description: 'Leiter einer THW-Führungsstelle im Einsatz', number: '97', code: '97' },
	{ description: 'S6/Fernmeldeführer', number: '98', code: '98' }
];

export const examples = [
	{ description: 'OV Schweinfurt - 1. TZ - Zugführer', callsign: 'HEROS Schweinfurt 21/91' },
	{ description: 'OV Barth - Bergungsgruppe 1. TZ - GKW', callsign: 'HEROS Barth 22/51' },
	{
		description: 'OV Dortmund - 2. Bergungsgruppe im 1. TZ - Truppführer',
		callsign: 'HEROS Dortmund 23/92'
	},
	{
		description: 'OV Leipzig - FGr Notversorgung/Notinstandsetzung im 2. TZ - MzGW',
		callsign: 'HEROS Leipzig 28/55'
	},
	{ description: 'OV Nürnberg - 3. TZ - Zugtruppführer', callsign: 'HEROS Nürnberg 71/92' },
	{ description: 'OV Bayreuth - OV-Stab - MTW', callsign: 'HEROS Bayreuth 86/25' },
	{
		description: 'OV Münster - Fachgruppe Kommunikation Typ B - MastKW',
		callsign: 'HEROS Münster 19/17'
	},
	{
		description: 'OV Quedlinburg - Fachgruppe Logistik-Materialwirtschaft - Gruppenführer',
		callsign: 'HEROS Quedlinburg 63/91'
	},
	{ description: 'OV Aurich - Fachgruppe Logistik-Verpflegung', callsign: 'HEROS Aurich 64/00' },
	{
		description: 'OV Jülich - THW-Führungsstelle als Einsatzleitung im Einsatz',
		callsign: 'HEROS Jülich 10/00'
	},
	{
		description: 'Bereitstellungsraum Nürburgring in einem Einsatzabschnitt im Einsatz',
		callsign: 'HEROS Nürburg 12/02'
	},
	{ description: 'Ein Bus des LV HHMVSH', callsign: 'HEROS Kiel 84/79' },
	{ description: 'OV Köln-Porz - Ortsbeauftragter', callsign: 'HEROS Köln 7/86/91' }
];

export const commonLocations = [
	'Aachen',
	'Augsburg',
	'Berlin',
	'Bielefeld',
	'Bochum',
	'Bonn',
	'Braunschweig',
	'Bremen',
	'Chemnitz',
	'Dortmund',
	'Dresden',
	'Düsseldorf',
	'Duisburg',
	'Erfurt',
	'Essen',
	'Frankfurt',
	'Freiburg',
	'Gelsenkirchen',
	'Hagen',
	'Halle',
	'Hamburg',
	'Hannover',
	'Heidelberg',
	'Heilbronn',
	'Karlsruhe',
	'Kassel',
	'Kiel',
	'Köln',
	'Krefeld',
	'Leipzig',
	'Lübeck',
	'Ludwigshafen',
	'Magdeburg',
	'Mainz',
	'Mannheim',
	'Mönchengladbach',
	'Mülheim',
	'München',
	'Münster',
	'Nürnberg',
	'Oberhausen',
	'Oldenburg',
	'Osnabrück',
	'Paderborn',
	'Pforzheim',
	'Potsdam',
	'Recklinghausen',
	'Regensburg',
	'Remscheid',
	'Reutlingen',
	'Rostock',
	'Saarbrücken',
	'Salzgitter',
	'Schweinfurt',
	'Solingen',
	'Stuttgart',
	'Ulm',
	'Wiesbaden',
	'Wolfsburg',
	'Wuppertal',
	'Würzburg'
];
