services:
  # Backend API
  backend:
    image: thw-tools-backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      platforms:
        - linux/amd64
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      KINDE_DOMAIN: ${KINDE_DOMAIN}
      RESEND_API_KEY: ${RESEND_API_KEY}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             node dist/main.js"
    ports:
      - '3000:3000'
    restart: always

  # THW-Tools Frontend
  thw-tools:
    image: thw-tools
    build:
      context: .
      dockerfile: apps/thw-tools/Dockerfile
      platforms:
        - linux/amd64
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL}
        PUBLIC_UMAMI_ENDPOINT: ${PUBLIC_UMAMI_ENDPOINT}
        PUBLIC_UMAMI_WEBSITEID: ${PUBLIC_UMAMI_WEBSITEID_THW_TOOLS}
    container_name: thw-tools-frontend
    environment:
      NODE_ENV: production

    # depends_on:
    #   - backend
    ports:
      - '3001:3000'
    restart: always

  # Inventar Frontend
  inventar:
    image: thw-inventar
    build:
      context: .
      dockerfile: apps/inventar/Dockerfile
      platforms:
        - linux/amd64
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL}
        PUBLIC_KINDE_API_CLIENT: ${PUBLIC_KINDE_API_CLIENT}
        PUBLIC_KINDE_DOMAIN: ${PUBLIC_KINDE_DOMAIN}
        PUBLIC_UMAMI_ENDPOINT: ${PUBLIC_UMAMI_ENDPOINT}
        PUBLIC_UMAMI_WEBSITEID: ${PUBLIC_UMAMI_WEBSITEID_INVENTAR}
    container_name: thw-inventar-frontend
    environment:
      NODE_ENV: production
    # depends_on:
    #   - backend
    ports:
      - '3002:3000'
    restart: always
