version: '3.8'

services:
  # Backend API
  backend:
    image: thw-tools-backend:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate deploy &&
             node dist/main.js"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - default
    ports:
      - published: 3000
        target: 3000
        protocol: tcp
        mode: ingress
    extra_hosts:
      - 'database:10.0.0.136'

  # THW-Tools Frontend
  thw-tools:
    image: thw-tools:latest
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_UMAMI_ENDPOINT=${PUBLIC_UMAMI_ENDPOINT}
      - PUBLIC_UMAMI_WEBSITEID=${PUBLIC_UMAMI_WEBSITEID_THW_TOOLS}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - published: 3001
        target: 3000
        protocol: tcp
        mode: ingress

  # Inventar Frontend
  inventar:
    image: thw-inventar:latest
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_KINDE_API_CLIENT=${PUBLIC_KINDE_API_CLIENT}
      - PUBLIC_KINDE_DOMAIN=${PUBLIC_KINDE_DOMAIN}
      - PUBLIC_UMAMI_ENDPOINT=${PUBLIC_UMAMI_ENDPOINT}
      - PUBLIC_UMAMI_WEBSITEID=${PUBLIC_UMAMI_WEBSITEID_INVENTAR}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - published: 3002
        target: 3000
        protocol: tcp
        mode: ingress

networks:
  default:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: ''
